export const GET_ERRORS = 'GET_ERRORS';
export const ADD_NEW_APPLICATION_FORM = 'ADD_NEW_APPLICATION_FORM';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const CHECK_IF_EMAIL_EXISTS_FROM_USERS = 'CHECK_IF_EMAIL_EXISTS_FROM_USERS';
export const CHECK_IF_EMAIL_EXISTS_FROM_APPLICATIOS = 'CHECK_IF_EMAIL_EXISTS_FROM_APPLICATIOS';
export const LOGIN = 'LOGIN';
